import numpy as np
import matplotlib.pyplot as plt

plt.figure(figsize=(8,6), dpi=80)
plt.subplot(1,1,1)
log_l = np.load("2.1.3_Log_loss.npy")
lin_l = np.load("2.1.3_Lin_loss.npy")
plt.plot(log_l, linewidth=1.0, linestyle='-', label="Logistic Regression Cross-Entropy Loss")
plt.plot(lin_l, linewidth=1.0, linestyle='-', label="Linear Regression MSE Loss")
plt.title("Logistic vs Linear Regression Training Set Loss", fontsize=10)
plt.xlabel("# of Epochs")
plt.ylabel("Training Loss (Cross-Entropy Loss)")
plt.legend(title="Data Set Loss", loc="upper right")
plt.grid('on', linestyle='-', linewidth=0.5)
plt.savefig("lin_vs_log_loss.pdf", format="pdf")

plt.figure(figsize=(8,6), dpi=80)
plt.subplot(1,1,1)
# log_v = np.load("2.1.3_Log_valid_acc.npy")
# log_te = np.load("2.1.3_Log_test_acc.npy")
log_tr = np.load("2.1.3_Log_train_acc.npy")
# lin_v = np.load("2.1.3_Lin_v_acc.npy")
lin_t = np.load("2.1.3_Lin_t_acc.npy")
plt.plot(log_tr, linewidth=1.0, linestyle='-', label="Logistic Regression")
plt.plot(lin_t, linewidth=1.0, linestyle='-', label="Linear Regression")
plt.title("Logistic vs Linear Regression Training Set Accuracy", fontsize=10)
plt.xlabel("# of Epochs")
plt.ylabel("Accuracy (Percentage Correct)")
plt.legend(title="Data Set Accuracy", loc="lower right")
plt.grid('on', linestyle='-', linewidth=0.5)
plt.savefig("lin_vs_log_acc.pdf", format="pdf")
